---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Apache install
      service: 
        - name: httpd
          state: stopped
      notify:
        - stop apache
#  handlers:
 #   - name: stop apache
  #    yum:
   #     - name: httpd
    #      state: removed
