---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install nginx
      yum: 
        name=nginx
        state=present
      notify:
        - start nginx
    #- name: static website
     # copy:
      #  src: static-site/
       # dest: /usr/share/nginx/www/
     # become: yes
  handlers:
    - name: start nginx
      service: name=nginx state=started
