---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: UnInstall nginx
      service: 
        name=nginx
        state=stopped
      notify:
        - remove nginx
  handlers:
    - name: remove nginx
      yum: name=nginx state=removed
